Add blog and update materials
Kirill19837/tutor-site pull request #28
Opened 2024-04-24 13:49 UTC by AndriyBoichuk

2024-04-24 13:58 UTC, Kirill19837 approved these changes

2024-04-25 07:15 UTC, newmasterSG requested changes

2024-04-25 07:15 UTC, newmasterSG commented on TutorPro.Application/Services/MaterialsService.cs
> +            using (var client = new HttpClient())
Maybe it is better use https://learn.microsoft.com/en-us/dotnet/core/extensions/httpclient-factory

2024-04-25 07:15 UTC, newmasterSG commented on TutorPro.Application/Interfaces/IMaterialsService.cs
> +        public Task<FilterResponse> GetMaterials(string searchText, string subject, string grade, string level, string sort, int page = 1, int pageSize = 12);
Delete public at public Task<FilterResponse> because public accessor by default

2024-04-25 07:15 UTC, newmasterSG commented on TutorPro.Application/Services/MaterialsService.cs
> +            if (!string.IsNullOrEmpty(subject) || !string.IsNullOrEmpty(grade) || !string.IsNullOrEmpty(level))
Maybe separate if clauses, because you use again these if clauses

2024-04-25 07:15 UTC, newmasterSG commented on TutorPro.Application/Services/MaterialsService.cs
> +                    if (response.IsSuccessStatusCode)
Write somethink like this 
```
if(!response.IsSuccessStatusCode){
 var errorMessage = $"Failed to retrieve materials from API. Status code: {response.StatusCode}";
                        _logger.LogError(errorMessage);
                        throw new Exception(errorMessage);
]
```
your code ..

2024-04-25 13:08 UTC, Kirill19837 requested changes

2024-04-25 13:08 UTC, Kirill19837 commented on TutorPro.Application/Services/MaterialsService.cs
> +            var apiUrl = "https://tutorpro.team/api/trpc/availableMaterial.getPublicMaterials";
add to backoffice

2024-04-25 13:37 UTC, Kirill19837 approved these changes

2024-04-25 13:39 UTC, Kirill19837 approved these changes

2024-04-25 13:46 UTC, newmasterSG approved these changes

2024-04-25 13:46 UTC, merged